spring.application.name=ocrbackend
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ocr_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

tesseract.datapath=${TESSERACT_DATAPATH:C:\Program Files\Tesseract-OCR\tessdata}
openai.api.key=${OPENAI_API_KEY:}
alpr.ml.base-url=${ALPR_ML_BASE_URL:http://localhost:8000}
alpr.fallback.openai.enabled=${ALPR_FALLBACK_OPENAI_ENABLED:false}
